Mb customer api
Ducky-Chickens/bangazon-API-sprint1 pull request #56
Opened 2018-03-23 20:52 UTC by melissabell456

## Changes:
- dev can access customers, one customer, post new customer, and change the first and last name of existing customer
## To Test:
run `nodemon app.js`

### in postman
#### PUT: 
localhost:8080/api/customers/
    `{
    "customer_id": 1,
      "first_name": "Anna",
      "last_name": "Carter"
    }`
Customer with id of 1's name should change to Anna Carter

#### POST:
localhost:8080/api/customers/
    {
      "first_name": "Betty",
      "last_name": "Boop",
      "join_date": "2010-08-16"
    }
New customer will be added with active status of 1 (true)

### in browser:
#### GET: http://10.0.0.45:8080/api/customers/
#### GET 1: http://10.0.0.45:8080/api/customers/2

2018-03-23 22:10 UTC, hunterphillips requested changes
nvm

2018-03-23 23:22 UTC, hunterphillips approved these changes

2018-03-26 13:51 UTC, dhazlettjr approved these changes
PUT- working
POST - working

**please remove / from edit and post in customers routing**

2018-03-26 14:08 UTC, electriceeli approved these changes
All tests passed ✔️

2018-03-26 14:11 UTC, merged